"""adiciona codigo de ativacao ao usuario

Revision ID: 7cfb74542084
Revises: 5fcddf9283ef
Create Date: 2026-08-13 10:34:10.083321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cfb74542084"
down_revision: Union[str, Sequence[str], None] = "5fcddf9283ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usuario",
        sa.Column("codigo_ativacao_hash", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "codigo_ativacao_hash")
    # ### end Alembic commands ###
