"""cria detalhe tecon e suas linhas

Revision ID: b941bba1882e
Revises: eb6f25372f82
Create Date: 2026-08-14 16:12:58.234681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b941bba1882e"
down_revision: Union[str, Sequence[str], None] = "eb6f25372f82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passagem_tecon_detalhe",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("passagem_id", sa.UUID(), nullable=False),
        sa.Column("houve_atendimento", sa.Boolean(), nullable=False),
        sa.Column("carga_mal_posicionada", sa.Boolean(), nullable=True),
        sa.Column("carga_mal_posicionada_descricao", sa.Text(), nullable=True),
        sa.Column("area1_atendida", sa.Boolean(), nullable=True),
        sa.Column("area1_inicio", sa.Time(), nullable=True),
        sa.Column("area1_termino", sa.Time(), nullable=True),
        sa.Column("area2_atendida", sa.Boolean(), nullable=True),
        sa.Column("area2_inicio", sa.Time(), nullable=True),
        sa.Column("area2_termino", sa.Time(), nullable=True),
        sa.ForeignKeyConstraint(["passagem_id"], ["passagem_servico.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("passagem_id"),
    )
    op.execute(
        """
        INSERT INTO linha (id, terminal, codigo, permite_sup_inf) VALUES
        ('00000000-0000-4000-8000-000000000101', 'TECON', 'Viaduto/DM1A', false),
        ('00000000-0000-4000-8000-000000000102', 'TECON', 'L1', false),
        ('00000000-0000-4000-8000-000000000103', 'TECON', 'L2', false),
        ('00000000-0000-4000-8000-000000000104', 'TECON', 'Travessão', false),
        ('00000000-0000-4000-8000-000000000105', 'TECON', 'DM4', false),
        ('00000000-0000-4000-8000-000000000106', 'TECON', 'DM6', false),
        ('00000000-0000-4000-8000-000000000107', 'TECON', 'DM1', false),
        ('00000000-0000-4000-8000-000000000108', 'TECON', 'DM3', false),
        ('00000000-0000-4000-8000-000000000109', 'TECON', 'Funil/DM2', false)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM linha WHERE terminal = 'TECON'")
    op.drop_table("passagem_tecon_detalhe")
    # ### end Alembic commands ###
