"""cria estrutura da passagem brisamar

Revision ID: eb6f25372f82
Revises: 7cfb74542084
Create Date: 2026-08-13 11:26:55.329267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb6f25372f82"
down_revision: Union[str, Sequence[str], None] = "7cfb74542084"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linha",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "terminal",
            sa.Enum("BRISAMAR", "TECON", name="terminal"),
            nullable=False,
        ),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("permite_sup_inf", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "terminal", "codigo", name="uq_linha_terminal_codigo"
        ),
    )
    op.execute(
        """
        INSERT INTO linha (id, terminal, codigo, permite_sup_inf) VALUES
        ('00000000-0000-4000-8000-000000000016', 'BRISAMAR', '16', false),
        ('00000000-0000-4000-8000-000000000018', 'BRISAMAR', '18', false),
        ('00000000-0000-4000-8000-000000000020', 'BRISAMAR', '20', false),
        ('00000000-0000-4000-8000-000000000022', 'BRISAMAR', '22', true),
        ('00000000-0000-4000-8000-000000000024', 'BRISAMAR', '24', true),
        ('00000000-0000-4000-8000-000000000026', 'BRISAMAR', '26', false),
        ('00000000-0000-4000-8000-000000000028', 'BRISAMAR', '28', false),
        ('00000000-0000-4000-8000-000000000030', 'BRISAMAR', '30', false)
        """
    )
    op.create_table('radio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('passagem_servico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terminal', sa.Enum('BRISAMAR', 'TECON', name='terminal'), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('responsavel_id', sa.UUID(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('relatorio_ocorrencias', sa.Text(), nullable=True),
    sa.Column('mobile_utilizado', sa.Boolean(), nullable=False),
    sa.Column('mobile_justificativa', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe_membro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passagem_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagem_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passagem_brisamar_detalhe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passagem_id', sa.UUID(), nullable=False),
    sa.Column('radios_operantes', sa.Integer(), nullable=False),
    sa.Column('radios_inoperantes', sa.Integer(), nullable=False),
    sa.Column('baterias', sa.Integer(), nullable=False),
    sa.Column('carregadores', sa.Integer(), nullable=False),
    sa.Column('eots_disponiveis', sa.Text(), nullable=True),
    sa.Column('eots_avariados', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagem_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passagem_id')
    )
    op.create_table('passagem_linha_ocupacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passagem_id', sa.UUID(), nullable=False),
    sa.Column('linha_id', sa.UUID(), nullable=False),
    sa.Column('veiculos', sa.Text(), nullable=True),
    sa.Column('sup_inf', sa.Enum('SUP', 'INF', name='ladolinha'), nullable=True),
    sa.ForeignKeyConstraint(['linha_id'], ['linha.id'], ),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagem_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'passagem_id',
        'linha_id',
        name='uq_passagem_linha_ocupacao_passagem_linha',
    )
    )
    op.create_table('passagem_radio_uso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passagem_id', sa.UUID(), nullable=False),
    sa.Column('radio_id', sa.UUID(), nullable=False),
    sa.Column('manobrador_nome', sa.String(), nullable=False),
    sa.Column('hora_retirada', sa.Time(), nullable=True),
    sa.Column('hora_entrega', sa.Time(), nullable=True),
    sa.Column('apresentou_falha', sa.Boolean(), nullable=False),
    sa.Column('falha_descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagem_servico.id'], ),
    sa.ForeignKeyConstraint(['radio_id'], ['radio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passagem_radio_uso')
    op.drop_table('passagem_linha_ocupacao')
    op.drop_table('passagem_brisamar_detalhe')
    op.drop_table('equipe_membro')
    op.drop_table('passagem_servico')
    op.drop_table('radio')
    op.drop_table('linha')
    op.execute("DROP TYPE ladolinha")
    op.execute("DROP TYPE terminal")
    # ### end Alembic commands ###
